[project]
name = "gymnasium-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium>=1.2.1",
    "matplotlib>=3.10.7",
    "stable-baselines3[extra]>=2.7.0",
    "tqdm>=4.67.1",
]
